DROP TABLE IF EXISTS Language;

CREATE TABLE Language 
(
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
NativeText NVARCHAR(254),
De NVARCHAR(254),
En NVARCHAR(254),
Fr NVARCHAR(254),
Sp NVARCHAR(254),
Ru NVARCHAR(254)
);


INSERT INTO [Language] ([NativeText],[De],[En],[Fr],[Sp],[Ru]) VALUES ('NativeText','De','En','Fr','Sp','Ru');
INSERT INTO [Language] ([NativeText],[De],[En],[Fr],[Sp],[Ru]) VALUES ('Aus[nl]Gebläse','Aus[nl]Gebläse','From[nl]Blower',NULL,NULL,'.юбьторпеавап');
INSERT INTO [Language] ([NativeText],[De],[En],[Fr],[Sp],[Ru]) VALUES ('Heizung','Heizung','Heat',NULL,NULL,'фывфвф');
INSERT INTO [Language] ([NativeText],[De],[En],[Fr],[Sp],[Ru]) VALUES ('Luft','Luft','Air',NULL,NULL,NULL);
INSERT INTO [Language] ([NativeText],[De],[En],[Fr],[Sp],[Ru]) VALUES ('Wasser','Wasser','Water',NULL,NULL,'фвфвфкуцерап');
INSERT INTO [Language] ([NativeText],[De],[En],[Fr],[Sp],[Ru]) VALUES ('Aus','Aus','Off',NULL,NULL,'араракенуфвфыпав');
INSERT INTO [Language] ([NativeText],[De],[En],[Fr],[Sp],[Ru]) VALUES ('Menue','Menue','Menu',NULL,NULL,'араракенуфвфыпав');
INSERT INTO [Language] ([NativeText],[De],[En],[Fr],[Sp],[Ru]) VALUES ('Sprache','Sprache','Language',NULL,NULL,'араракенуфвфыпав');
INSERT INTO [Language] ([NativeText],[De],[En],[Fr],[Sp],[Ru]) VALUES ('Datenausgabe','Datenausgabe','Output data',NULL,NULL,'араракенуфвфыпав');
INSERT INTO [Language] ([NativeText],[De],[En],[Fr],[Sp],[Ru]) VALUES ('Passworteingabe','Passworteingabe','Enter Password',NULL,NULL,'выылнекуцуыфва');
INSERT INTO [Language] ([NativeText],[De],[En],[Fr],[Sp],[Ru]) VALUES ('Passwort:','Passwort:','Password:',NULL,NULL,'цукенгшльотрип');
INSERT INTO [Language] ([NativeText],[De],[En],[Fr],[Sp],[Ru]) VALUES ('Tastatur','Tastatur','Keyboard',NULL,NULL,'араракенуфвфыпав');
INSERT INTO [Language] ([NativeText],[De],[En],[Fr],[Sp],[Ru]) VALUES ('Programm beenden?','Programm beenden?','Exit Program?',NULL,NULL,'длгонекпуц');
INSERT INTO [Language] ([NativeText],[De],[En],[Fr],[Sp],[Ru]) VALUES ('Programm beenden','Programm beenden','Exit Program',NULL,NULL,'йцукенпгршщз');
INSERT INTO [Language] ([NativeText],[De],[En],[Fr],[Sp],[Ru]) VALUES ('Benutzer:','Benutzer:','User:',NULL,NULL,NULL);
INSERT INTO [Language] ([NativeText],[De],[En],[Fr],[Sp],[Ru]) VALUES ('Operator','Operator','Operator',NULL,NULL,NULL);
INSERT INTO [Language] ([NativeText],[De],[En],[Fr],[Sp],[Ru]) VALUES ('Ausgeloggt','Ausgeloggt','Logoff',NULL,NULL,NULL);
INSERT INTO [Language] ([NativeText],[De],[En],[Fr],[Sp],[Ru]) VALUES ('Service','Service','Service',NULL,NULL,NULL);
INSERT INTO [Language] ([NativeText],[De],[En],[Fr],[Sp],[Ru]) VALUES ('Pumpen 1','Pumpen 1','Pumps 1',NULL,NULL,NULL);
INSERT INTO [Language] ([NativeText],[De],[En],[Fr],[Sp],[Ru]) VALUES ('Einrichter','Einrichter','Setter',NULL,NULL,NULL);
INSERT INTO [Language] ([NativeText],[De],[En],[Fr],[Sp],[Ru]) VALUES ('Fehler 1','Fehler 1','Error 1',NULL,NULL,NULL);
INSERT INTO [Language] ([NativeText],[De],[En],[Fr],[Sp],[Ru]) VALUES ('Seite 1','Seite 1','Page 1',NULL,NULL,NULL);


CREATE TABLE IF NOT EXISTS Parameter  
(
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
Parameter NVARCHAR(254),
Value NVARCHAR(254),
Comment NVARCHAR(254)
);


INSERT INTO Parameter(Parameter,Value,Comment)
SELECT 'Language','De','System'
WHERE NOT EXISTS(SELECT 1 FROM Parameter WHERE Parameter = 'Language');

CREATE TABLE IF NOT EXISTS Errors  
(
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
InComing  timestamp,
OutGoing  timestamp,
VisuSymbol NVARCHAR(20)
);


DROP TABLE IF EXISTS Plcitems;

CREATE TABLE Plcitems 
(
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
S7Adress NVARCHAR(20),
S7Symbol NVARCHAR(20),
S7SymbolType NVARCHAR(10),
S7Comment NVARCHAR(150),
SymbolType NVARCHAR(150),
Column NVARCHAR(10),
RankingGroup NVARCHAR(150),
GroupComment NVARCHAR(150),
RankingSymbol NVARCHAR(150),
Comment NVARCHAR(150),
Unit NVARCHAR(150),
SymbolFormat NVARCHAR(150),
UpperLimit NVARCHAR(150),
LowerLimit NVARCHAR(150),
UserRightEnable NVARCHAR(150),
UserRightVisible NVARCHAR(150),
VisuSymbol NVARCHAR(20)
);

INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB50.DBD0','P1_Qmin_1','REAL','Pumpen 1:Pumpendruck 1','S','1','1','Pumpen 1','1','Pumpendruck 1','bar','0.0','99999','0','14','15','DB50.P1_Qmin_1');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB50.DBD4','P1_Qmin_2','REAL','Pumpen 1:Pumpendruck 2','S','1','1','Pumpen 1','2','Pumpendruck 2','bar','0.00','99999','0','15','15','DB50.P1_Qmin_2');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB50.DBD8','P1_Qmin_3','REAL','Pumpen 1:Pumpendruck 3','S','1','1','Pumpen 1','3','Pumpendruck 3','bar','0.00','99999','0','15','15','DB50.P1_Qmin_3');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB50.DBD12','P1_Qmin_4','REAL','Pumpen 1:Pumpendruck 4','S','1','1','Pumpen 1','4','Pumpendruck 4','bar','0','99999','0','15','15','DB50.P1_Qmin_4');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB50.DBD16','P1_Qmin_5','REAL','Pumpen 1:Pumpendruck 5','S','1','1','Pumpen 1','5','Pumpendruck 5','bar','0.00','99999','0','15','15','DB50.P1_Qmin_5');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB51.DBD0','P1_Qmin_1','REAL','Pumpen 2:Pumpendruck 1','I','1','2','Pumpen 2','1','Pumpendruck 1','bar','0.00','99999','0','14','15','DB51.P1_Qmin_1');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB51.DBD4','P1_Qmin_2','REAL','Pumpen 2:Pumpendruck 2','I','1','2','Pumpen 2','2','Pumpendruck 2','bar','0.0','99999','0','14','15','DB51.P1_Qmin_2');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB51.DBD8','P1_Qmin_3','REAL','Pumpen 2:Pumpendruck 3','I','1','2','Pumpen 2','3','Pumpendruck 3','bar','0.00','99999','0','14','15','DB51.P1_Qmin_3');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB51.DBD12','P1_Qmin_4','REAL','Pumpen 2:Pumpendruck 4','I','1','2','Pumpen 2','4','Pumpendruck 4','bar','0.00','99999','0','14','15','DB51.P1_Qmin_4');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB51.DBD16','P1_Qmin_5','REAL','Pumpen 2:Pumpendruck 5','I','1','2','Pumpen 2','5','Pumpendruck 5','bar','0.00','99999','0','14','15','DB51.P1_Qmin_5');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB52.DBW0','Valve01','INT','Schieber:Status 1','I','1','3','Schieber','1','Status 1',NULL,'0','99999','0','15','15','DB52.Valve01');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB52.DBW2','Valve02','INT','Schieber:Status 2','I','1','3','Schieber','2','Status 2',NULL,'0','99999','0','15','15','DB52.Valve02');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB52.DBW4','Valve03','INT','Schieber:Status 3','I','1','3','Schieber','3','Status 3',NULL,'0','99999','0','15','15','DB52.Valve03');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB52.DBW6','Valve04','INT','Schieber:Status 4','I','1','3','Schieber','4','Status 4',NULL,'0','99999','0','15','15','DB52.Valve04');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB52.DBW8','Valve05','INT','Schieber:Status 5','I','1','3','Schieber','5','Status 5',NULL,'0','99999','0','15','15','DB52.Valve05');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX0.0','Bit01','BOOL','Fehlergruppe 1: Fehler 1','I','1','4','Fehlergruppe 1','1','Fehler 1',NULL,'0','1','0','15','15','DB53.Bit01');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX0.1','Bit02','BOOL','Fehlergruppe 1: Fehler 2','I','1','4','Fehlergruppe 1','2','Fehler 2',NULL,'0','1','0','15','15','DB53.Bit02');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX0.2','Bit03','BOOL','Fehlergruppe 1: Fehler 3','I','1','4','Fehlergruppe 1','3','Fehler 3',NULL,'0','1','0','15','15','DB53.Bit03');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX0.3','Bit04','BOOL','Fehlergruppe 1: Fehler 4','I','1','4','Fehlergruppe 1','4','Fehler 4',NULL,'0','1','0','15','15','DB53.Bit04');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX0.4','Bit05','BOOL','Fehlergruppe 1: Fehler 5','E','1','4','Fehlergruppe 1','5','Fehler 5',NULL,'0','1','0','15','15','DB53.Bit05');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX0.5','Bit06','BOOL','Fehlergruppe 1: Fehler 6','E','1','4','Fehlergruppe 1','6','Fehler 6',NULL,'0','1','0','15','15','DB53.Bit06');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX0.6','Bit07','BOOL','Fehlergruppe 1: Fehler 7','E','1','4','Fehlergruppe 1','7','Fehler 7',NULL,'0','1','0','15','15','DB53.Bit07');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX0.7','Bit08','BOOL','Fehlergruppe 1: Fehler 8','E','1','4','Fehlergruppe 1','8','Fehler 8',NULL,'0','1','0','15','15','DB53.Bit08');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX1.0','Bit09','BOOL','Fehlergruppe 2: Fehler 1','E','1','5','Fehlergruppe 2','1','Fehler 1',NULL,'0','1','0','15','15','DB53.Bit09');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX1.1','Bit10','BOOL','Fehlergruppe 2: Fehler 2','E','1','5','Fehlergruppe 2','2','Fehler 2',NULL,'0','1','0','15','15','DB53.Bit10');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX1.2','Bit11','BOOL','Fehlergruppe 2: Fehler 3','E','1','5','Fehlergruppe 2','3','Fehler 3',NULL,'0','1','0','15','15','DB53.Bit11');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX1.3','Bit12','BOOL','Fehlergruppe 2: Fehler 4','E','1','5','Fehlergruppe 2','4','Fehler 4',NULL,'0','1','0','15','15','DB53.Bit12');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX1.4','Bit13','BOOL','Fehlergruppe 2: Fehler 5','E','1','5','Fehlergruppe 2','5','Fehler 5',NULL,'0','1','0','15','15','DB53.Bit13');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX1.5','Bit14','BOOL','Fehlergruppe 2: Fehler 6','E','1','5','Fehlergruppe 2','6','Fehler 6',NULL,'0','1','0','15','15','DB53.Bit14');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX1.6','Bit15','BOOL','Fehlergruppe 2: Fehler 7','E','1','5','Fehlergruppe 2','7','Fehler 7',NULL,'0','1','0','15','15','DB53.Bit15');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX1.7','Bit16','BOOL','Fehlergruppe 2: Fehler 8','E','1','5','Fehlergruppe 2','8','Fehler 8',NULL,'0','1','0','15','15','DB53.Bit16');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX2.0','Bit17','BOOL','Fehlergruppe 3: Fehler 1','E','1','6','Fehlergruppe 3','1','Fehler 1',NULL,'0','1','0','15','15','DB53.Bit17');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX2.1','Bit18','BOOL','Fehlergruppe 3: Fehler 2','E','1','6','Fehlergruppe 3','2','Fehler 2',NULL,'0','1','0','15','15','DB53.Bit18');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX2.2','Bit19','BOOL','Fehlergruppe 3: Fehler 3','E','1','6','Fehlergruppe 3','3','Fehler 3',NULL,'0','1','0','15','15','DB53.Bit19');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX2.3','Bit20','BOOL','Fehlergruppe 3: Fehler 4','E','1','6','Fehlergruppe 3','4','Fehler 4',NULL,'0','1','0','15','15','DB53.Bit20');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX2.4','Bit21','BOOL','Fehlergruppe 3: Fehler 5','E','1','6','Fehlergruppe 3','5','Fehler 5',NULL,'0','1','0','15','15','DB53.Bit21');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX2.5','Bit22','BOOL','Fehlergruppe 3: Fehler 6','E','1','6','Fehlergruppe 3','6','Fehler 6',NULL,'0','1','0','15','15','DB53.Bit22');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX2.6','Bit23','BOOL','Fehlergruppe 3: Fehler 7','E','1','6','Fehlergruppe 3','7','Fehler 7',NULL,'0','1','0','15','15','DB53.Bit23');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX2.7','Bit24','BOOL','Fehlergruppe 3: Fehler 8','E','1','6','Fehlergruppe 3','8','Fehler 8',NULL,'0','1','0','15','15','DB53.Bit24');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX3.0','Bit25','BOOL','Fehlergruppe 4: Fehler 1','E','1','7','Fehlergruppe 4','1','Fehler 1',NULL,'0','1','0','15','15','DB53.Bit25');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX3.1','Bit26','BOOL','Fehlergruppe 4: Fehler 2','E','1','7','Fehlergruppe 4','2','Fehler 2',NULL,'0','1','0','15','15','DB53.Bit26');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX3.2','Bit27','BOOL','Fehlergruppe 4: Fehler 3','E','1','7','Fehlergruppe 4','3','Fehler 3',NULL,'0','1','0','15','15','DB53.Bit27');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX3.3','Bit28','BOOL','Fehlergruppe 4: Fehler 4','E','1','7','Fehlergruppe 4','4','Fehler 4',NULL,'0','1','0','15','15','DB53.Bit28');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX3.4','Bit29','BOOL','Fehlergruppe 4: Fehler 5','E','1','7','Fehlergruppe 4','5','Fehler 5',NULL,'0','1','0','15','15','DB53.Bit29');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX3.5','Bit30','BOOL','Fehlergruppe 4: Fehler 6','E','1','7','Fehlergruppe 4','6','Fehler 6',NULL,'0','1','0','15','15','DB53.Bit30');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX3.6','Bit31','BOOL','Fehlergruppe 4: Fehler 7','E','1','7','Fehlergruppe 4','7','Fehler 7',NULL,'0','1','0','15','15','DB53.Bit31');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB53.DBX3.7','Bit32','BOOL','Fehlergruppe 4: Fehler 8','E','1','7','Fehlergruppe 4','8','Fehler 8',NULL,'0','1','0','15','15','DB53.Bit32');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX0.0','Bit01','BOOL','Freigabegruppe 1: Freigabe 1','R','1','8','Freigabegruppe 1','1','Freigabe 1',NULL,'0','1','0','15','15','DB54.Bit01');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX0.1','Bit02','BOOL','Freigabegruppe 1: Freigabe 2','R','1','8','Freigabegruppe 1','2','Freigabe 2',NULL,'0','1','0','15','15','DB54.Bit02');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX0.2','Bit03','BOOL','Freigabegruppe 1: Freigabe 3','R','1','8','Freigabegruppe 1','3','Freigabe 3',NULL,'0','1','0','15','15','DB54.Bit03');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX0.3','Bit04','BOOL','Freigabegruppe 1: Freigabe 4','R','1','8','Freigabegruppe 1','4','Freigabe 4',NULL,'0','1','0','15','15','DB54.Bit04');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX0.4','Bit05','BOOL','Freigabegruppe 1: Freigabe 5','R','1','8','Freigabegruppe 1','5','Freigabe 5',NULL,'0','1','0','15','15','DB54.Bit05');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX0.5','Bit06','BOOL','Freigabegruppe 1: Freigabe 6','R','1','8','Freigabegruppe 1','6','Freigabe 6',NULL,'0','1','0','15','15','DB54.Bit06');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX0.6','Bit07','BOOL','Freigabegruppe 1: Freigabe 7','R','1','8','Freigabegruppe 1','7','Freigabe 7',NULL,'0','1','0','15','15','DB54.Bit07');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX0.7','Bit08','BOOL','Freigabegruppe 1: Freigabe 8','R','1','8','Freigabegruppe 1','8','Freigabe 8',NULL,'0','1','0','15','15','DB54.Bit08');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX1.0','Bit09','BOOL','Freigabegruppe 1: Freigabe 9','R','1','8','Freigabegruppe 1','9','Freigabe 9',NULL,'0','1','0','15','15','DB54.Bit09');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX1.1','Bit10','BOOL','Freigabegruppe 1: Freigabe 10','R','1','8','Freigabegruppe 1','10','Freigabe 10',NULL,'0','1','0','15','15','DB54.Bit10');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX1.2','Bit11','BOOL','Freigabegruppe 1: Freigabe 11','R','1','8','Freigabegruppe 1','11','Freigabe 11',NULL,'0','1','0','15','15','DB54.Bit11');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX1.3','Bit12','BOOL','Freigabegruppe 1: Freigabe 12','R','1','8','Freigabegruppe 1','12','Freigabe 12',NULL,'0','1','0','15','15','DB54.Bit12');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX1.4','Bit13','BOOL','Freigabegruppe 1: Freigabe 13','R','1','8','Freigabegruppe 1','13','Freigabe 13',NULL,'0','1','0','15','15','DB54.Bit13');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX1.5','Bit14','BOOL','Freigabegruppe 1: Freigabe 14','R','1','8','Freigabegruppe 1','14','Freigabe 14',NULL,'0','1','0','15','15','DB54.Bit14');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX1.6','Bit15','BOOL','Freigabegruppe 1: Freigabe 15','R','1','8','Freigabegruppe 1','15','Freigabe 15',NULL,'0','1','0','15','15','DB54.Bit15');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX1.7','Bit16','BOOL','Freigabegruppe 1: Freigabe 16','R','1','8','Freigabegruppe 1','16','Freigabe 16',NULL,'0','1','0','15','15','DB54.Bit16');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX2.0','Bit17','BOOL','Freigabegruppe 2: Freigabe 1','R','1','9','Freigabegruppe 2','1','Freigabe 1',NULL,'0','1','0','15','15','DB54.Bit17');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX2.1','Bit18','BOOL','Freigabegruppe 2: Freigabe 2','R','1','9','Freigabegruppe 2','2','Freigabe 2',NULL,'0','1','0','15','15','DB54.Bit18');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX2.2','Bit19','BOOL','Freigabegruppe 2: Freigabe 3','R','1','9','Freigabegruppe 2','3','Freigabe 3',NULL,'0','1','0','15','15','DB54.Bit19');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX2.3','Bit20','BOOL','Freigabegruppe 2: Freigabe 4','R','1','9','Freigabegruppe 2','4','Freigabe 4',NULL,'0','1','0','15','15','DB54.Bit20');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX2.4','Bit21','BOOL','Freigabegruppe 2: Freigabe 5','R','1','9','Freigabegruppe 2','5','Freigabe 5',NULL,'0','1','0','15','15','DB54.Bit21');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX2.5','Bit22','BOOL','Freigabegruppe 2: Freigabe 6','R','1','9','Freigabegruppe 2','6','Freigabe 6',NULL,'0','1','0','15','15','DB54.Bit22');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX2.6','Bit23','BOOL','Freigabegruppe 2: Freigabe 7','R','1','9','Freigabegruppe 2','7','Freigabe 7',NULL,'0','1','0','15','15','DB54.Bit23');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX2.7','Bit24','BOOL','Freigabegruppe 2: Freigabe 8','R','1','9','Freigabegruppe 2','8','Freigabe 8',NULL,'0','1','0','15','15','DB54.Bit24');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX3.0','Bit25','BOOL','Freigabegruppe 2: Freigabe 9','R','1','9','Freigabegruppe 2','9','Freigabe 9',NULL,'0','1','0','15','15','DB54.Bit25');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX3.1','Bit26','BOOL','Freigabegruppe 2: Freigabe 10','R','1','9','Freigabegruppe 2','10','Freigabe 10',NULL,'0','1','0','15','15','DB54.Bit26');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX3.2','Bit27','BOOL','Freigabegruppe 2: Freigabe 11','R','1','9','Freigabegruppe 2','11','Freigabe 11',NULL,'0','1','0','15','15','DB54.Bit27');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX3.3','Bit28','BOOL','Freigabegruppe 2: Freigabe 12','R','1','9','Freigabegruppe 2','12','Freigabe 12',NULL,'0','1','0','15','15','DB54.Bit28');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX3.4','Bit29','BOOL','Freigabegruppe 2: Freigabe 13','R','1','9','Freigabegruppe 2','13','Freigabe 13',NULL,'0','1','0','15','15','DB54.Bit29');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX3.5','Bit30','BOOL','Freigabegruppe 2: Freigabe 14','R','1','9','Freigabegruppe 2','14','Freigabe 14',NULL,'0','1','0','15','15','DB54.Bit30');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX3.6','Bit31','BOOL','Freigabegruppe 2: Freigabe 15','R','1','9','Freigabegruppe 2','15','Freigabe 15',NULL,'0','1','0','15','15','DB54.Bit31');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB54.DBX3.7','Bit32','BOOL','Freigabegruppe 2: Freigabe 16','R','1','9','Freigabegruppe 2','16','Freigabe 16',NULL,'0','1','0','15','15','DB54.Bit32');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBX0.0','Bit01','BOOL','Fehlergruppe 1: Fehler 1','P','1','3','Fehlergruppe 1','1','Fehler 1',NULL,'0','1','0','15','15','DB55.Bit01');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBX0.1','Bit02','BOOL','Fehlergruppe 1: Fehler 2','P','1','3','Fehlergruppe 1','2','Fehler 2',NULL,'0','1','0','15','15','DB55.Bit02');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBX0.2','Bit03','BOOL','Fehlergruppe 1: Fehler 3','P','1','3','Fehlergruppe 1','3','Fehler 3',NULL,'0','1','0','15','15','DB55.Bit03');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBX0.3','Bit04','BOOL','Fehlergruppe 1: Fehler 4','P','1','3','Fehlergruppe 1','4','Fehler 4',NULL,'0','1','0','15','15','DB55.Bit04');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBX0.4','Bit05','BOOL','Fehlergruppe 1: Fehler 5','P','1','3','Fehlergruppe 1','5','Fehler 5',NULL,'0','1','0','15','15','DB55.Bit05');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBX0.5','Bit06','BOOL','Fehlergruppe 1: Fehler 6','P','1','3','Fehlergruppe 1','6','Fehler 6',NULL,'0','1','0','14','15','DB55.Bit06');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD2','Wert1','REAL','Parameter:Wert1 Real','P','1','4','Parameter','1','Wert1 Real','bar','0.0','99999','0','15','15','DB55.Wert1');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBW6','Wert2','INT','Parameter:Wert2 Int','P','1','4','Parameter','2','Wert2 Int','mm','0','99999','0','14','15','DB55.Wert2');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD8','Wert3','REAL','Parameter:Wert3 Real','P','1','4','Parameter','3','Wert3 Real','m','0','99999','0','12','15','DB55.Wert3');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBW12','Wert4','INT','Parameter:Wert4 Int','P','1','4','Parameter','4','Wert4 Int','s','0','99999','0','8','15','DB55.Wert4');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD14','Wert5','REAL','Parameter:Wert5 Real','P','1','4','Parameter','5','Wert5 Real','%','0.00','99999','0','14','15','DB55.Wert5');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD18','Burner00','REAL','Burner: Stufe 0',NULL,'1','5','Burner','1','Stufe 0','%','0.00','20','0','8','15','DB55.Burner00');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD22','Burner01','REAL','Burner: Stufe 1',NULL,'1','5','Burner','2','Stufe 1','%','0.00','20','0','8','15','DB55.Burner01');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD26','Burner02','REAL','Burner: Stufe 2',NULL,'1','5','Burner','3','Stufe 2','%','0.00','20','0','8','15','DB55.Burner02');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD30','Burner03','REAL','Burner: Stufe 3',NULL,'1','5','Burner','4','Stufe 3','%','0.00','20','0','8','15','DB55.Burner03');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD34','Burner04','REAL','Burner: Stufe 4',NULL,'1','5','Burner','5','Stufe 4','%','0.00','20','0','8','15','DB55.Burner04');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD38','Burner05','REAL','Burner: Stufe 5',NULL,'1','5','Burner','6','Stufe 5','%','0.00','20','0','8','15','DB55.Burner05');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD42','Burner06','REAL','Burner: Stufe 6',NULL,'1','5','Burner','7','Stufe 6','%','0.00','20','0','8','15','DB55.Burner06');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD46','Burner07','REAL','Burner: Stufe 7',NULL,'1','5','Burner','8','Stufe 7','%','0.00','20','0','8','15','DB55.Burner07');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD50','Burner08','REAL','Burner: Stufe 8',NULL,'1','5','Burner','9','Stufe 8','%','0.00','20','0','8','15','DB55.Burner08');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD54','Burner09','REAL','Burner: Stufe 9',NULL,'1','5','Burner','10','Stufe 9','%','0.00','20','0','8','15','DB55.Burner09');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD58','Burner10','REAL','Burner: Stufe 10',NULL,'1','5','Burner','11','Stufe 10','%','0.00','20','0','4','15','DB55.Burner10');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD62','Burner11','REAL','Burner: Stufe 11',NULL,'1','5','Burner','12','Stufe 11','%','0.00','20','0','4','15','DB55.Burner11');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD66','Burner12','REAL','Burner: Stufe 12',NULL,'1','5','Burner','13','Stufe 12','%','0.00','20','0','4','15','DB55.Burner12');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD70','Burner13','REAL','Burner: Stufe 13',NULL,'1','5','Burner','14','Stufe 13','%','0.00','20','0','4','15','DB55.Burner13');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD74','Burner14','REAL','Burner: Stufe 14',NULL,'1','5','Burner','15','Stufe 14','%','0.00','20','0','4','15','DB55.Burner14');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD78','Burner15','REAL','Burner: Stufe 15',NULL,'1','5','Burner','16','Stufe 15','%','0.00','20','0','4','15','DB55.Burner15');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD82','Burner16','REAL','Burner: Stufe 16',NULL,'1','5','Burner','17','Stufe 16','%','0.00','20','0','4','15','DB55.Burner16');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD86','Burner17','REAL','Burner: Stufe 17',NULL,'1','5','Burner','18','Stufe 17','%','0.00','20','0','2','15','DB55.Burner17');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD90','Burner18','REAL','Burner: Stufe 18',NULL,'1','5','Burner','19','Stufe 18','%','0.00','20','0','2','15','DB55.Burner18');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD94','Burner19','REAL','Burner: Stufe 19',NULL,'1','5','Burner','20','Stufe 19','%','0.00','20','0','2','15','DB55.Burner19');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD98','Burner20','REAL','Burner: Stufe 20',NULL,'1','5','Burner','21','Stufe 20','%','0.00','20','0','2','15','DB55.Burner20');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD102','Fuel00','REAL','Burner: Stufe 21',NULL,'1','5','Burner','22','Stufe 21','%','0.00','20','0','2','15','DB55.Fuel00');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD106','Fuel01','REAL','Brennstoff: Stufe 5',NULL,'1','6','Brennstoff','1','Stufe 5',NULL,'0','20','0','15','15','DB55.Fuel01');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD110','Fuel02','REAL','Brennstoff: Stufe 10',NULL,'1','6','Brennstoff','2','Stufe 10',NULL,'0','20','0','15','15','DB55.Fuel02');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD114','Fuel03','REAL','Brennstoff: Stufe 15',NULL,'1','6','Brennstoff','3','Stufe 15',NULL,'0','20','0','15','15','DB55.Fuel03');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD118','Fuel04','REAL','Brennstoff: Stufe 20',NULL,'1','6','Brennstoff','4','Stufe 20',NULL,'0','20','0','15','15','DB55.Fuel04');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD122','Fuel05','REAL','Brennstoff: Stufe 25',NULL,'1','6','Brennstoff','5','Stufe 25',NULL,'0','20','0','15','15','DB55.Fuel05');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD126','Fuel06','REAL','Brennstoff: Stufe 30',NULL,'1','6','Brennstoff','6','Stufe 30',NULL,'0','20','0','15','15','DB55.Fuel06');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD130','Fuel07','REAL','Brennstoff: Stufe 35',NULL,'1','6','Brennstoff','7','Stufe 35',NULL,'0','20','0','15','15','DB55.Fuel07');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD134','Fuel08','REAL','Brennstoff: Stufe 40',NULL,'1','6','Brennstoff','8','Stufe 40',NULL,'0','20','0','15','15','DB55.Fuel08');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD138','Fuel09','REAL','Brennstoff: Stufe 45',NULL,'1','6','Brennstoff','9','Stufe 45',NULL,'0','20','0','15','15','DB55.Fuel09');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD142','Fuel10','REAL','Brennstoff: Stufe 50',NULL,'1','6','Brennstoff','10','Stufe 50',NULL,'0','20','0','15','15','DB55.Fuel10');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD146','Fuel11','REAL','Brennstoff: Stufe 55',NULL,'1','6','Brennstoff','11','Stufe 55',NULL,'0','20','0','15','15','DB55.Fuel11');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD150','Fuel12','REAL','Brennstoff: Stufe 60',NULL,'1','6','Brennstoff','12','Stufe 60',NULL,'0','20','0','15','15','DB55.Fuel12');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD154','Fuel13','REAL','Brennstoff: Stufe 65',NULL,'1','6','Brennstoff','13','Stufe 65',NULL,'0','20','0','15','15','DB55.Fuel13');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD158','Fuel14','REAL','Brennstoff: Stufe 70',NULL,'1','6','Brennstoff','14','Stufe 70',NULL,'0','20','0','15','15','DB55.Fuel14');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD162','Fuel15','REAL','Brennstoff: Stufe 75',NULL,'1','6','Brennstoff','15','Stufe 75',NULL,'0','20','0','15','15','DB55.Fuel15');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD166','Fuel16','REAL','Brennstoff: Stufe 80',NULL,'1','6','Brennstoff','16','Stufe 80',NULL,'0','20','0','15','15','DB55.Fuel16');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD170','Fuel17','REAL','Brennstoff: Stufe 85',NULL,'1','6','Brennstoff','17','Stufe 85',NULL,'0','20','0','15','15','DB55.Fuel17');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD174','Fuel18','REAL','Brennstoff: Stufe 90',NULL,'1','6','Brennstoff','18','Stufe 90',NULL,'0','20','0','15','15','DB55.Fuel18');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD178','Fuel19','REAL','Brennstoff: Stufe 95',NULL,'1','6','Brennstoff','19','Stufe 95',NULL,'0','20','0','15','15','DB55.Fuel19');
INSERT INTO [Plcitems] ([S7Adress],[S7Symbol],[S7SymbolType],[S7Comment],[SymbolType],[Column],[RankingGroup],[GroupComment],[RankingSymbol],[Comment],[Unit],[SymbolFormat],[UpperLimit],[LowerLimit],[UserRightEnable],[UserRightVisible],[VisuSymbol]) VALUES ('DB55.DBD182','Fuel20','REAL','Brennstoff: Stufe 100',NULL,'1','6','Brennstoff','20','Stufe 100',NULL,'0','20','0','15','15','DB55.Fuel20');


INSERT 
INTO Language (nativetext)
SELECT DISTINCT 
Plcitems.Comment AS NativeText
FROM         
Plcitems 
LEFT OUTER JOIN
Language 
ON 
Plcitems.Comment = Language.NativeText
WHERE     
Language.NativeText IS NULL
go

INSERT 
INTO Language (nativetext)
SELECT DISTINCT 
Plcitems.GroupComment AS NativeText
FROM         
Plcitems 
LEFT OUTER JOIN
Language 
ON 
Plcitems.GroupComment = Language.NativeText
WHERE     
Language.NativeText IS NULL
go

update language set de=nativetext where de is null
go
update language set sp=nativetext where sp is null
go
update language set fr=nativetext where fr is null
go
update language set en=nativetext where en is null
go
update language set ru=nativetext where ru is null
go
